language: julia
os: linux

julia:
        - 0.4
notifications:
        email: false

install:
        - julia -e 'Pkg.add("HDF5")'
        - julia -e 'Pkg.add("EMIRT")'
        - julia -e 'Pkg.checkout("EMIRT")'
        - julia -e 'Pkg.add("Watershed"); Pkg.checkout("Watershed")'

script:
        - julia -e 'Pkg.test("EMIRT")'
