language: julia
os: linux

julia:
        - 0.4
python: "2.7"

notifications:
        email: false

before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -qq update

install:
        - sudo apt-get install python2.7 python2.7-dev python-pip
        - sudo pip install --upgrade pip
        - sudo apt-get install -y gcc 
        - sudo apt-get install -y python-numpy python-matplotlib python-h5py
        - sudo pip install tifffile
        - julia -e 'Pkg.add("HDF5"); Pkg.add("Compose"); Pkg.add("PyPlot")'
        - git clone https://github.com/seung-lab/EMIRT.jl.git
        - mv EMIRT.jl ~/.julia/v0.4/EMIRT
        - git clone https://github.com/seung-lab/Watershed.jl.git
        - mv Watershed.jl ~/.julia/v0.4/Watershed
        

script:
        - cd ~/.julia/v0.4/EMIRT
        - git checkout parallel
        - julia -e 'Pkg.test("EMIRT")'
