language: julia
os: linux

julia:
        - 0.4
python: "2.7"

notifications:
        email: false

before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -qq update

install:
        - sudo apt-get install -y python-numpy python-tifffile python-matplotlib python-h5py
        - git clone https://github.com/seung-lab/EMIRT.jl.git
        - mv EMIRT.jl ~/.julia/v0.4/EMIRT

script:
        - julia -e `Pkg.test("EMIRT")`
