language: julia
os: linux

julia:
        - 0.4
notifications:
        email: false

install:
        - julia -e 'Pkg.add("HDF5"); Pkg.add("FileIO")'
        - julia -e 'Pkg.checkout("https://github.com/seung-lab/EMIRT.jl.git")'
        - julia -e 'Pkg.add("Watershed"); Pkg.checkout("Watershed")'

script:
        - julia -e 'Pkg.test("EMIRT")'
